openapi: 3.0.3
info:
  title: To-Do API
  version: 1.0.0
paths:
  /tasks/{id}:
    patch:
  summary: Update or toggle a task's 'completed' status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: Send { "completed": true } to set explicitly. If omitted, the status will be toggled.
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
      responses:
        '200':
          description: Task updated, returns the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid body
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
          nullable: true
        completed:
          type: boolean
        priority:
          type: string
          enum: [low, medium, high]
        created_at:
          type: string
          format: date-time